
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.util.Random;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import sun.audio.AudioPlayer;
import sun.audio.AudioStream;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author srlab2
 */
public class Audience_poll extends javax.swing.JFrame {
Timer t;
int s1=0;
int s2=0;
int s3=0;
int s4=0;
int crt=0;
public void cl(){
     this.dispose();
       }

    /**
     * Creates new form Audience_poll
     */
    public Audience_poll() {
        initComponents();
          getContentPane().setBackground(Color.BLACK);
          jLabel5.setText("");
          jLabel6.setText("");
          jLabel7.setText("");
          jLabel8.setText("");
          jButton1.setVisible(false);
          InputStream music;
          try{
         music=new FileInputStream(new File("src\\audio\\Audiencepollmusic.wav"));
         AudioStream audios=new AudioStream(music); 
         AudioPlayer.player.start(audios);   
          }
          catch(IOException m){JOptionPane.showMessageDialog(null,m.getMessage());}
          t=new Timer(100, new ActionListener(){
     @Override
            public void actionPerformed(ActionEvent e){
                crt++;
        if(crt==101)
          {
        t.stop();
        jProgressBar1.setValue(J12.A1);
        jProgressBar2.setValue(J12.B1);
        jProgressBar3.setValue(J12.C1);
        jProgressBar4.setValue(J12.D1);
        jLabel5.setText(J12.A1+"%");
        jLabel6.setText(J12.B1+"%");
        jLabel7.setText(J12.C1+"%");
        jLabel8.setText(J12.D1+"%");
        J12.A1=0;
        J12.B1=0;
        J12.C1=0;
        J12.D1=0;
        jButton1.setVisible(true);
        J12.M1=1;
          }
        else 
           {
              Random x=new Random();
              if(l1<=90&&l2<=90&&l3<=90&&l4<=90&&l1>=10&&l2>=10&&l3>=10&&l4>=10)
          {
                s1=x.nextInt(2);
                s2=x.nextInt(2);
                s3=x.nextInt(2);
                s4=x.nextInt(2);
          }
               else if(l1<10||l2<10||l3<10||l4<10)
                  {
                      s1=0;
                      s2=0;
                      s3=0;
                      s4=0;
                  }
               else if(l1>90||l2>90||l3>90||l4>90)                  {
                      s1=1;
                      s2=1;
                      s3=1;
                      s4=1;
                  }
               
                if(s1==0)
          {
              l1+=2;
              jProgressBar1.setValue(l1);
          }
                else
          {
              l1-=2;
              jProgressBar1.setValue(l1);            
          }
                if(s2==0)
          {
              l2+=2;
              jProgressBar2.setValue(l2);
          }
                else
          {
              l2-=2;
              jProgressBar2.setValue(l2);            
          }
                if(s3==0)
          {
              l3+=2;
              jProgressBar3.setValue(l3);
          }
                else
          {
              l3-=2;
              jProgressBar3.setValue(l3);            
          }
                if(s4==0)
          {
              l4+=2;
              jProgressBar4.setValue(l4);
          }
                else
          {
              l4-=2;
              jProgressBar4.setValue(l4);            
          }}
          }
          });t.start();
       }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        jProgressBar2 = new javax.swing.JProgressBar();
        jProgressBar3 = new javax.swing.JProgressBar();
        jProgressBar4 = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        getContentPane().setLayout(null);

        jProgressBar1.setValue(50);
        getContentPane().add(jProgressBar1);
        jProgressBar1.setBounds(72, 58, 146, 23);

        jProgressBar2.setValue(50);
        getContentPane().add(jProgressBar2);
        jProgressBar2.setBounds(72, 92, 146, 23);

        jProgressBar3.setValue(50);
        getContentPane().add(jProgressBar3);
        jProgressBar3.setBounds(72, 126, 146, 24);

        jProgressBar4.setValue(50);
        getContentPane().add(jProgressBar4);
        jProgressBar4.setBounds(72, 161, 146, 26);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 0));
        jLabel1.setText("A");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(44, 58, 10, 17);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 51, 0));
        jLabel2.setText("B");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(44, 92, 10, 17);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 51, 0));
        jLabel3.setText("C");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(44, 126, 10, 17);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 51, 0));
        jLabel4.setText("D");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(44, 161, 10, 17);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 51, 0));
        getContentPane().add(jLabel5);
        jLabel5.setBounds(228, 58, 46, 23);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 51, 0));
        getContentPane().add(jLabel6);
        jLabel6.setBounds(228, 92, 46, 23);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 51, 0));
        getContentPane().add(jLabel7);
        jLabel7.setBounds(228, 126, 46, 24);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 51, 0));
        getContentPane().add(jLabel8);
        jLabel8.setBounds(228, 161, 46, 26);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 51, 0));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Results of Audience Poll");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(40, 10, 216, 24);

        jButton1.setBackground(new java.awt.Color(255, 0, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(204, 204, 204));
        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(120, 200, 73, 25);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/yash_raj_logo - Copy.png"))); // NOI18N
        getContentPane().add(jLabel10);
        jLabel10.setBounds(255, 11, 37, 41);

        setBounds(270, 115, 318, 292);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        cl();
    }//GEN-LAST:event_jButton1ActionPerformed
int l1=40;
int l2=60;
int l4=30;
int l3=70;
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Audience_poll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Audience_poll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Audience_poll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Audience_poll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Audience_poll().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JProgressBar jProgressBar2;
    private javax.swing.JProgressBar jProgressBar3;
    private javax.swing.JProgressBar jProgressBar4;
    // End of variables declaration//GEN-END:variables
}
