
import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import java.awt.Color;
import java.sql.DriverManager;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author srlab5
 */
public class Forgot_Password extends javax.swing.JFrame {

    /**
     * Creates new form Forgot_Password
     */
    public Forgot_Password() {
        initComponents();
         getContentPane().setBackground(Color.BLACK);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jPasswordField2 = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 0));
        jLabel1.setText("Forgot Password");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(200, 30, 150, 22);

        jLabel2.setForeground(new java.awt.Color(0, 204, 204));
        jLabel2.setText("Enter User Id");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(60, 120, 140, 14);

        jLabel3.setForeground(new java.awt.Color(0, 204, 204));
        jLabel3.setText("Enter Mobile No");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(60, 300, 170, 14);

        jLabel4.setForeground(new java.awt.Color(0, 204, 204));
        jLabel4.setText("Enter new password");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(60, 180, 160, 14);

        jLabel5.setForeground(new java.awt.Color(0, 204, 204));
        jLabel5.setText("Cofirm new password");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(60, 240, 160, 14);

        jButton1.setBackground(new java.awt.Color(255, 0, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setForeground(new java.awt.Color(204, 204, 204));
        jButton1.setText("Change password");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(200, 381, 170, 23);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(270, 110, 136, 30);

        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField2KeyTyped(evt);
            }
        });
        getContentPane().add(jTextField2);
        jTextField2.setBounds(270, 290, 136, 30);
        getContentPane().add(jPasswordField1);
        jPasswordField1.setBounds(270, 170, 136, 31);
        getContentPane().add(jPasswordField2);
        jPasswordField2.setBounds(270, 230, 136, 30);

        jLabel6.setForeground(new java.awt.Color(0, 204, 204));
        jLabel6.setText("@kbc.com");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(430, 120, 120, 14);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/yash_raj_logo - Copy.png"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(525, 11, 37, 41);

        setSize(new java.awt.Dimension(589, 475));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
String EnteredId=jTextField1.getText()+"@kbc.com",EnteredMobi=jTextField2.getText(),newPassword1,newPassword2;
newPassword1=new String (jPasswordField1.getPassword());// TODO add your handling code here:
newPassword2=new String (jPasswordField2.getPassword());
if(newPassword1.equals(newPassword2))
{
   
   try
   {
       Class.forName("java.sql.DriverManager");
       Connection con= (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/yashraj","root", "joker");
       Statement stmt= (Statement) con.createStatement();
       String query="select * from users where mobile_no='"+EnteredMobi+"' and user_id='"+EnteredId+"';";
       ResultSet rs=stmt.executeQuery(query);
       if(rs.next())
       {
           try
           {
              Statement stmt2= (Statement) con.createStatement();
              String query2="Update users set password='"+newPassword1+"' where user_id='"+EnteredId+"';";
              stmt2.executeUpdate(query2);
           }
           catch(Exception p)
           {
               JOptionPane.showMessageDialog(this, p.getMessage());
           }
       JOptionPane.showMessageDialog(this,"Congratulation! you have successfully changed your password. \nNow login and start the game");
       Login_Page a= new Login_Page();
       a.setVisible(true);
       this.setVisible(false);
       }
       else
       {
           JOptionPane.showMessageDialog(this, "Please check your user id and Mobile no.");
           jTextField1.setText("");
           jTextField2.setText("");
           jPasswordField1.setText("");
           jPasswordField2.setText("");
           jTextField1.grabFocus();
       }
   }
   catch(Exception e)
   {
       JOptionPane.showMessageDialog(this, e.getMessage());
   }
}
else
{
    JOptionPane.showMessageDialog(this, "Passwords do not match");
    jPasswordField1.setText("");
    jPasswordField2.setText("");
    jPasswordField1.grabFocus();
}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyTyped
        // TODO add your handling code here:
        String s=jTextField2.getText();
        int l=s.length();
        if(l>9)
        {
            evt.consume();
        }
    }//GEN-LAST:event_jTextField2KeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Forgot_Password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Forgot_Password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Forgot_Password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Forgot_Password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Forgot_Password().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
