
import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.DriverManager;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author srlab5
 */
public class Price_Money extends javax.swing.JFrame {
 int cr=0;int m=0;
 public void cl(){
    t.stop();
    this.dispose();}
    /**
     * Creates new form Price_Money
     */
    public Price_Money() {
        initComponents();
        getContentPane().setBackground(Color.BLACK);
        jLabel6.setVisible(false);
        jTextField2.setVisible(false);
        jButton3.setVisible(false);
        try
        {
    Class.forName("java.sql.DriverManager");
    Connection con=(Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/yashraj", "root", "joker");
    Statement stmt1=(Statement) con.createStatement();
    String query="Select * from users where status!=0;";
    ResultSet rs=stmt1.executeQuery(query);
    if(rs.next())
    {
        String amt=rs.getString("amount");
        jLabel2.setText("Final amount is Rs. "+amt);
    }
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }
Timer t;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    int rt;
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().setLayout(null);

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setForeground(new java.awt.Color(51, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Enter Account No.");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(120, 190, 120, 14);

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 51, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(58, 11, 426, 68);

        jTextField1.setPreferredSize(new java.awt.Dimension(2, 23));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField1KeyTyped(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(300, 180, 150, 30);

        jButton1.setBackground(new java.awt.Color(255, 0, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(204, 204, 204));
        jButton1.setText("Submit");
        jButton1.setFocusPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(227, 267, 76, 23);

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(jLabel3);
        jLabel3.setBounds(41, 312, 520, 90);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/yash_raj_logo - Copy.png"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(530, 11, 36, 50);

        jComboBox1.setBackground(new java.awt.Color(0, 0, 0));
        jComboBox1.setEditable(true);
        jComboBox1.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "(Select a bank)", "ICICI Bank", "HDFC Bank", "Axis Bank", "State Bank of India", "Punjab National Bank", "Others" }));
        jComboBox1.setBorder(null);
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(300, 100, 150, 30);

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setForeground(new java.awt.Color(51, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Choose a Bank ");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(142, 109, 100, 14);

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setForeground(new java.awt.Color(51, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Enter Bank Name");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(130, 150, 110, 14);

        jTextField2.setPreferredSize(new java.awt.Dimension(2, 23));
        getContentPane().add(jTextField2);
        jTextField2.setBounds(299, 143, 150, 30);

        jButton3.setBackground(new java.awt.Color(255, 0, 0));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(204, 204, 204));
        jButton3.setText("Sign Out");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(220, 200, 90, 23);

        setSize(new java.awt.Dimension(592, 470));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
String a=jTextField1.getText(),Y="";
int b=jComboBox1.getSelectedIndex(),v=0;
switch(b)
{
    case 0: JOptionPane.showMessageDialog(this, "Please select a bank");
        v=1;break;
    case 1:  Y="ICICI Bank";break;   
    case 2:  Y="HDFC Bank";break;   
    case 3:  Y="Axis Bank";break;   
    case 4:  Y="State Bank Of India";break;   
    case 5:  Y="Punjab National Bank";break;
    case 6: Y=jTextField2.getText();
    if(Y.isEmpty())
    {
         JOptionPane.showMessageDialog(this, "Please enter bank name");
     v=2;
    } break;
    default: break;
}
if(v==0)
{
try
{
    Class.forName("java.sql.DriverManager");
    Connection c=(Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/yashraj", "root", "joker");
    Statement d=(Statement) c.createStatement();
    String q="Select * from users where status!=0";
    ResultSet e=d.executeQuery(q);
    if(e.next())
    {
        String f=e.getString(1);
        int g=e.getInt(6);
        try
        {
            Statement h=(Statement) c.createStatement();
            String query="Insert into price_money values ('"+f+"',"+g+","+a+",0,'"+Y+"');";
            h.executeUpdate(query);
        }
        catch (Exception h)
        {
            JOptionPane.showMessageDialog(this, h.getMessage());
        }
    }
}
catch (Exception e)
{
    JOptionPane.showMessageDialog(this, e.getMessage());
}
    rt=6;
             t=new Timer(500, new ActionListener(){
     @Override
     
            public void actionPerformed(ActionEvent e){
        if(rt>=1)
        {
         if(rt%3==0)    {  
                jLabel3.setText("Please wait while your transaction is being processed.");
          }
         else if(rt%3==2)    {  
                jLabel3.setText("Please wait while your transaction is being processed..");
          }
         else if(rt%3==1)    {  
                jLabel3.setText("Please wait while your transaction is being processed...");
          }
         rt--;
        }
        else
        { 
             jButton3.setText("Sign Out");
             jButton1.setText("");
              jButton3.setContentAreaFilled(true);
              jButton3.setVisible(true);
              jButton1.setContentAreaFilled(false);
              jButton3.setEnabled(true);
              jButton1.setEnabled(false);
              jLabel1.setVisible(false);
              jLabel2.setVisible(false);
              jLabel3.setVisible(false);
             
              jLabel5.setVisible(false);
              jLabel6.setVisible(false);
              jTextField1.setVisible(false);
              jTextField2.setVisible(false);
              jComboBox1.setVisible(false);
              
              
              
            JOptionPane.showMessageDialog(null, "Your Transaction is Succesful");
            jLabel1.setText("");
            int x=JOptionPane.showConfirmDialog(null, "Do you want to play again?", "Confirm", JOptionPane.YES_NO_OPTION);
            if(x==1)
            {
            jButton3.setEnabled(true);
                JOptionPane.showMessageDialog(null, "please click on the Sign Out button");
                t.stop();
            }
            else
            {
                Welcome_Page y=new Welcome_Page();
                y.setVisible(true);
                 cl();
            }
        }
        }});t.start();

}
else if(v==2)
{
    jComboBox1.setSelectedIndex(6);
}
else
{
    jComboBox1.setSelectedIndex(0);
}

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyTyped
String a=jTextField1.getText();
int x=a.length();
if(x<10)
{
int b=evt.getKeyChar();
if(b>=48&&b<=57)
{
}
else
{
    evt.consume();
}
}
else
{
    evt.consume(); 
}
    }//GEN-LAST:event_jTextField1KeyTyped

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
if(jComboBox1.getSelectedIndex()==6)  
{
    jLabel6.setVisible(true);
    jTextField2.setVisible(true);
}
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try
        {
    Class.forName("java.sql.DriverManager");
    Connection c=(Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/yashraj", "root", "joker");
    Statement d=(Statement) c.createStatement();
    String q="Update users set status=0 and amount=0 where status!=0";
    d.executeUpdate(q);
        }
        catch (Exception e)
        {
           JOptionPane.showMessageDialog(this, e.getMessage()); 
        }
        Thank_You a=new Thank_You();
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Price_Money.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Price_Money.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Price_Money.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Price_Money.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Price_Money().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
