
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.Timer;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author srlab5
 */
public class Rule_Page extends javax.swing.JFrame {

    /**
     * Creates new form Rule_Page
     */
    public Rule_Page() {
        initComponents();
        jTextArea1.setBackground(Color.BLACK);
        getContentPane().setBackground(Color.BLACK);
        jLabel2.setVisible(false);
        jLabel3.setVisible(false);
        jLabel4.setVisible(false);
        jLabel5.setVisible(false);
        jRadioButton1.setVisible(false);
        jRadioButton2.setVisible(false);
        jRadioButton3.setVisible(false);
        jRadioButton4.setVisible(false);
        jRadioButton5.setVisible(false);
        jRadioButton6.setVisible(false);
        jRadioButton7.setVisible(false);
        jRadioButton8.setVisible(false);
        jRadioButton9.setVisible(false);
        jRadioButton10.setVisible(false);
        jRadioButton11.setVisible(false);
        jRadioButton12.setVisible(false);
        jRadioButton13.setVisible(false);
        jRadioButton14.setVisible(false);
        jRadioButton15.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        jRadioButton8 = new javax.swing.JRadioButton();
        jRadioButton9 = new javax.swing.JRadioButton();
        jRadioButton10 = new javax.swing.JRadioButton();
        jRadioButton11 = new javax.swing.JRadioButton();
        jRadioButton12 = new javax.swing.JRadioButton();
        jRadioButton13 = new javax.swing.JRadioButton();
        jRadioButton14 = new javax.swing.JRadioButton();
        jRadioButton15 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jButton1.setBackground(new java.awt.Color(255, 0, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(204, 204, 204));
        jButton1.setText("Next");
        jButton1.setFocusPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(143, 503, 60, 23);

        jButton2.setBackground(new java.awt.Color(255, 0, 0));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(204, 204, 204));
        jButton2.setText("Back");
        jButton2.setFocusPainted(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(49, 503, 60, 23);

        jButton3.setBackground(new java.awt.Color(255, 0, 0));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(204, 204, 204));
        jButton3.setText("Back to Home");
        jButton3.setFocusPainted(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(235, 503, 117, 23);

        jRadioButton1.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jRadioButton1.setText("          5,000");
        jRadioButton1.setContentAreaFilled(false);
        getContentPane().add(jRadioButton1);
        jRadioButton1.setBounds(802, 444, 101, 23);

        jScrollPane1.setBorder(null);

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("DejaVu Sans Mono", 1, 18)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(255, 51, 51));
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText("Press the Back button to view previous rule.\nPress the Next button to view next rule.\nPress the Back to Home button to return to the Welcome Page.");
        jTextArea1.setWrapStyleWord(true);
        jTextArea1.setBorder(null);
        jTextArea1.setFocusable(false);
        jTextArea1.setOpaque(false);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 70, 630, 310);

        jRadioButton2.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jRadioButton2.setText("        10,000");
        jRadioButton2.setContentAreaFilled(false);
        getContentPane().add(jRadioButton2);
        jRadioButton2.setBounds(802, 421, 101, 23);

        jRadioButton3.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jRadioButton3.setText("        20,000");
        jRadioButton3.setContentAreaFilled(false);
        getContentPane().add(jRadioButton3);
        jRadioButton3.setBounds(802, 398, 101, 23);

        jRadioButton4.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jRadioButton4.setText("        40,000");
        jRadioButton4.setContentAreaFilled(false);
        getContentPane().add(jRadioButton4);
        jRadioButton4.setBounds(802, 375, 101, 23);

        jRadioButton5.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(jRadioButton5);
        jRadioButton5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jRadioButton5.setText("        80,000");
        jRadioButton5.setContentAreaFilled(false);
        getContentPane().add(jRadioButton5);
        jRadioButton5.setBounds(802, 352, 101, 23);

        jRadioButton6.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(jRadioButton6);
        jRadioButton6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jRadioButton6.setText("     1,60,000");
        jRadioButton6.setContentAreaFilled(false);
        getContentPane().add(jRadioButton6);
        jRadioButton6.setBounds(802, 329, 101, 23);

        jRadioButton7.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(jRadioButton7);
        jRadioButton7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jRadioButton7.setText("     3,20,000");
        jRadioButton7.setContentAreaFilled(false);
        getContentPane().add(jRadioButton7);
        jRadioButton7.setBounds(802, 306, 101, 23);

        jRadioButton8.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(jRadioButton8);
        jRadioButton8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jRadioButton8.setText("     6,40,000");
        jRadioButton8.setContentAreaFilled(false);
        getContentPane().add(jRadioButton8);
        jRadioButton8.setBounds(802, 283, 101, 23);

        jRadioButton9.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(jRadioButton9);
        jRadioButton9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jRadioButton9.setText("   12,50,000");
        jRadioButton9.setContentAreaFilled(false);
        getContentPane().add(jRadioButton9);
        jRadioButton9.setBounds(802, 260, 101, 23);

        jRadioButton10.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(jRadioButton10);
        jRadioButton10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jRadioButton10.setText("   25,00,000");
        jRadioButton10.setContentAreaFilled(false);
        getContentPane().add(jRadioButton10);
        jRadioButton10.setBounds(802, 237, 101, 23);

        jRadioButton11.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(jRadioButton11);
        jRadioButton11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jRadioButton11.setText("   50,00,000");
        jRadioButton11.setContentAreaFilled(false);
        getContentPane().add(jRadioButton11);
        jRadioButton11.setBounds(802, 214, 101, 23);

        jRadioButton12.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(jRadioButton12);
        jRadioButton12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jRadioButton12.setText("1,00,00,000");
        jRadioButton12.setContentAreaFilled(false);
        getContentPane().add(jRadioButton12);
        jRadioButton12.setBounds(802, 191, 101, 23);

        jRadioButton13.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(jRadioButton13);
        jRadioButton13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jRadioButton13.setText("3,00,00,000");
        jRadioButton13.setContentAreaFilled(false);
        getContentPane().add(jRadioButton13);
        jRadioButton13.setBounds(802, 168, 101, 23);

        jRadioButton14.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(jRadioButton14);
        jRadioButton14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jRadioButton14.setText("5,00,00,000");
        jRadioButton14.setContentAreaFilled(false);
        getContentPane().add(jRadioButton14);
        jRadioButton14.setBounds(802, 145, 101, 23);

        jRadioButton15.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(jRadioButton15);
        jRadioButton15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jRadioButton15.setText("7,00,00,000");
        jRadioButton15.setContentAreaFilled(false);
        getContentPane().add(jRadioButton15);
        jRadioButton15.setBounds(802, 122, 101, 23);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/yash_raj_logo - Copy.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(870, 20, 40, 50);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/power papplu button.PNG"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(650, 270, 120, 40);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/audience poll button.PNG"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(650, 150, 120, 40);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/Flip button.PNG"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(660, 190, 100, 40);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/50-50 button.PNG"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(670, 230, 90, 40);

        setSize(new java.awt.Dimension(957, 581));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
 int a=0;int r=0,x=0;Timer t,h;
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        a++;  r=0;
        if(a>5)
        {
            a=6;
        }
        switch(a)
        {
            case 1: jTextArea1.setText("The game will take you through 15 questions demarcated with prize money as shown beside. Each Question will have 4 options out of which only 1 is correct.");
       
            t=new Timer(500, new ActionListener(){
     @Override
            public void actionPerformed(ActionEvent e){
          r++;
               switch (r)
               {
                   case 0:break;
                   case 1:jRadioButton1.setVisible(true);
                   jRadioButton1.setContentAreaFilled(true);
                   jRadioButton1.setSelected(true);
                   jRadioButton1.setForeground(new Color(204,51,0));break;
                   case 2:jRadioButton2.setVisible(true);
                   jRadioButton2.setContentAreaFilled(true);
                   jRadioButton2.setSelected(true);
                   jRadioButton2.setForeground(new Color(204,51,0));
                   jRadioButton1.setForeground(Color.cyan);break;
                   case 3:jRadioButton3.setVisible(true);
                   jRadioButton3.setContentAreaFilled(true);
                   jRadioButton3.setSelected(true);
                   jRadioButton3.setForeground(new Color(204,51,0));
                   jRadioButton2.setForeground(Color.cyan);break;
                   case 4:jRadioButton4.setVisible(true);
                   jRadioButton4.setContentAreaFilled(true);
                   jRadioButton4.setSelected(true);
                   jRadioButton4.setForeground(new Color(204,51,0));
                   jRadioButton3.setForeground(Color.cyan);break;
                   case 5:jRadioButton5.setVisible(true);
                   jRadioButton5.setContentAreaFilled(true);
                   jRadioButton5.setSelected(true);
                   jRadioButton5.setForeground(new Color(204,51,0));
                   jRadioButton4.setForeground(Color.cyan);break;
                   case 6:jRadioButton6.setVisible(true);
                   jRadioButton6.setContentAreaFilled(true);
                   jRadioButton6.setSelected(true);
                   jRadioButton6.setForeground(new Color(204,51,0));
                   jRadioButton5.setForeground(Color.cyan);break;
                   case 7:jRadioButton7.setVisible(true);
                   jRadioButton7.setContentAreaFilled(true);
                   jRadioButton7.setSelected(true);
                   jRadioButton7.setForeground(new Color(204,51,0));
                   jRadioButton6.setForeground(Color.cyan);break;
                   case 8:jRadioButton8.setVisible(true);
                   jRadioButton8.setContentAreaFilled(true);
                   jRadioButton8.setSelected(true);
                   jRadioButton8.setForeground(new Color(204,51,0));
                   jRadioButton7.setForeground(Color.cyan);break;
                   case 9:jRadioButton9.setVisible(true);
                   jRadioButton9.setContentAreaFilled(true);
                   jRadioButton9.setSelected(true);
                   jRadioButton9.setForeground(new Color(204,51,0));
                   jRadioButton8.setForeground(Color.cyan);break;
                   case 10:jRadioButton10.setVisible(true);
                   jRadioButton10.setContentAreaFilled(true);
                   jRadioButton10.setSelected(true);
                   jRadioButton10.setForeground(new Color(204,51,0));
                   jRadioButton9.setForeground(Color.cyan);break;
                   case 11:jRadioButton11.setVisible(true);
                   jRadioButton11.setContentAreaFilled(true);
                   jRadioButton11.setSelected(true);
                   jRadioButton11.setForeground(new Color(204,51,0));
                   jRadioButton10.setForeground(Color.cyan);break;
                   case 12:jRadioButton12.setVisible(true);
                   jRadioButton12.setContentAreaFilled(true);
                   jRadioButton12.setSelected(true);
                   jRadioButton12.setForeground(new Color(204,51,0));
                   jRadioButton11.setForeground(Color.cyan);break;
                   case 13:jRadioButton13.setVisible(true);
                   jRadioButton13.setContentAreaFilled(true);
                   jRadioButton13.setSelected(true);
                   jRadioButton13.setForeground(new Color(204,51,0));
                   jRadioButton12.setForeground(Color.cyan);break;
                   case 14:jRadioButton14.setVisible(true);
                   jRadioButton14.setContentAreaFilled(true);
                   jRadioButton14.setSelected(true);
                   jRadioButton14.setForeground(new Color(204,51,0));
                   jRadioButton13.setForeground(Color.cyan);break;
                   case 15:jRadioButton15.setVisible(true);
                   jRadioButton15.setContentAreaFilled(true);
                   jRadioButton15.setSelected(true);
                   jRadioButton15.setForeground(new Color(204,51,0));
                   jRadioButton14.setForeground(Color.cyan);break;
                   case 16:jRadioButton15.setForeground(Color.cyan);buttonGroup1.clearSelection();break;
                   default: break;
               }
     }
     });
        t.start();  break;
        case 2: jTextArea1.setText("The first 6 questions will be under a timer of 60 seconds.\nThe next 5 questions will be under a timer of 90 seconds.\nThe last 4 questions will not be timer bound. ");
                  buttonGroup1.clearSelection();    
                    t.stop();
                    jRadioButton1.setVisible(true);
                    jRadioButton2.setVisible(true);
                    jRadioButton3.setVisible(true);
                    jRadioButton4.setVisible(true);
                    jRadioButton5.setVisible(true);
                    jRadioButton6.setVisible(true);
                    jRadioButton7.setVisible(true);
                    jRadioButton8.setVisible(true);
                    jRadioButton9.setVisible(true);
                    jRadioButton10.setVisible(true);
                    jRadioButton11.setVisible(true);
                    jRadioButton12.setVisible(true);
                    jRadioButton13.setVisible(true);
                    jRadioButton14.setVisible(true);
                    jRadioButton15.setVisible(true);
                    jRadioButton1.setForeground(Color.cyan);
                    jRadioButton2.setForeground(Color.cyan);
                    jRadioButton3.setForeground(Color.cyan);
                    jRadioButton4.setForeground(Color.cyan);
                    jRadioButton5.setForeground(Color.cyan);
                    jRadioButton6.setForeground(Color.cyan);
                    jRadioButton7.setForeground(Color.cyan);
                    jRadioButton8.setForeground(Color.cyan);
                    jRadioButton9.setForeground(Color.cyan);
                    jRadioButton10.setForeground(Color.cyan);
                    jRadioButton11.setForeground(Color.cyan);
                    jRadioButton12.setForeground(Color.cyan);
                    jRadioButton13.setForeground(Color.cyan);
                    jRadioButton14.setForeground(Color.cyan);
                    jRadioButton15.setForeground(Color.cyan);
                    jRadioButton1.setContentAreaFilled(true);
                    jRadioButton2.setContentAreaFilled(true);
                    jRadioButton3.setContentAreaFilled(true);
                    jRadioButton4.setContentAreaFilled(true);
                    jRadioButton5.setContentAreaFilled(true);
                    jRadioButton6.setContentAreaFilled(true);
                    jRadioButton7.setContentAreaFilled(true);
                    jRadioButton8.setContentAreaFilled(true);
                    jRadioButton9.setContentAreaFilled(true);
                    jRadioButton10.setContentAreaFilled(true);
                    jRadioButton11.setContentAreaFilled(true);
                    jRadioButton12.setContentAreaFilled(true);
                    jRadioButton13.setContentAreaFilled(true);
                    jRadioButton14.setContentAreaFilled(true);
                    jRadioButton15.setContentAreaFilled(true);
            break;
            case 3: jTextArea1.setText("The game has two safety 'Padaos' and reaching them will ensure that you win atleast that much prize money.\n The first padao is at the 6th question with a prize money of Rs 1,60,000. \n The second padao is at the 11th question with a prize money of Rs 50,00,000. ");
                    jRadioButton6.setForeground(Color.red);
                    jRadioButton11.setForeground(Color.red);
                    jRadioButton15.setForeground(Color.red);
                    t.stop();
            break;
            case 5:
                jTextArea1.setText("If you are stuck with any question there are 4 lifelines to help you out. They are - \n 1) Audience Poll - \nThis lifeline will carry out an online voting , the results of which will be displayed on the screen. \n 2) Flip -\nThis lifeline allows you to change the question.  \n 3) 50-50 -\nThis lifeline will eliminate 2 incorrect options.\n 4) Power - Paplu -\n This lifeline will allow you to revive 1 of the above given lifelines");
                h=new Timer(500, new ActionListener(){
     @Override
                public void actionPerformed(ActionEvent e){
                x++;
         switch (x)
         {
             case 1:jLabel3.setVisible(true);break;
             case 2:jLabel4.setVisible(true);break;
             case 3:jLabel5.setVisible(true);break;
             case 4:jLabel2.setVisible(true);break;
             default: h.stop();x=0;break;
         }
     }
       });h.start();t.stop(); break;
            case 4: jTextArea1.setText("Sufficient time has been given to all the questions, so think well before you answer as givng a wrong answer will reduce the value of your prize money as set by the padaos.\nYou can also quit if not sure about the answer to leave with the amount you have won till then. ");
        t.stop();    break;
            default:t.stop();h.stop();x=0;
            jLabel2.setVisible(false);
            jLabel3.setVisible(false);
            jLabel4.setVisible(false);
            jLabel5.setVisible(false);
            jRadioButton1.setVisible(false);
            jRadioButton2.setVisible(false);
            jRadioButton3.setVisible(false);
            jRadioButton4.setVisible(false);
            jRadioButton5.setVisible(false);
            jRadioButton6.setVisible(false);
            jRadioButton7.setVisible(false);
            jRadioButton8.setVisible(false);
            jRadioButton9.setVisible(false);
            jRadioButton10.setVisible(false);
            jRadioButton11.setVisible(false);
            jRadioButton12.setVisible(false);
            jRadioButton13.setVisible(false);
            jRadioButton14.setVisible(false);
            jRadioButton15.setVisible(false);
            jTextArea1.setText("Press the Back button to view previous rule\nPress the Next button to view next rule\nPress the Back to Home button to return to the Welcome Page");
        }
        if(a==0)
        {
        jButton2.setVisible(false);
        jLabel2.setVisible(false);
        jLabel3.setVisible(false);
        jLabel4.setVisible(false);
        jLabel5.setVisible(false);
        jRadioButton1.setVisible(false);
        jRadioButton2.setVisible(false);
        jRadioButton3.setVisible(false);
        jRadioButton4.setVisible(false);
        jRadioButton5.setVisible(false);
        jRadioButton6.setVisible(false);
        jRadioButton7.setVisible(false);
        jRadioButton8.setVisible(false);
        jRadioButton9.setVisible(false);
        jRadioButton10.setVisible(false);
        jRadioButton11.setVisible(false);
        jRadioButton12.setVisible(false);
        jRadioButton13.setVisible(false);
        jRadioButton14.setVisible(false);
        jRadioButton15.setVisible(false);
        }
        else
        {
            jButton2.setVisible(true);
        }
        if(a==6)
        {
        jButton1.setVisible(false);
        jLabel2.setVisible(false);
        jLabel3.setVisible(false);
        jLabel4.setVisible(false);
        jLabel5.setVisible(false);
        jRadioButton1.setVisible(false);
        jRadioButton2.setVisible(false);
        jRadioButton3.setVisible(false);
        jRadioButton4.setVisible(false);
        jRadioButton5.setVisible(false);
        jRadioButton6.setVisible(false);
        jRadioButton7.setVisible(false);
        jRadioButton8.setVisible(false);
        jRadioButton9.setVisible(false);
        jRadioButton10.setVisible(false);
        jRadioButton11.setVisible(false);
        jRadioButton12.setVisible(false);
        jRadioButton13.setVisible(false);
        jRadioButton14.setVisible(false);
        jRadioButton15.setVisible(false);
        }
        else
        {
            jButton1.setVisible(true);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        a--; r=0;
        if(a<1)
        {
            a=0;
        }
        switch(a)
        {
            case 1: jTextArea1.setText("The game will take you through 15 questions demarcated with prize money a shown beside. Each Question will have 4 options out of which only 1 is correct.");
            t=new Timer(500, new ActionListener(){
     @Override
            public void actionPerformed(ActionEvent e){
          r++;
               switch (r)
               {
                   case 0:break;
                   case 1:jRadioButton1.setVisible(true);
                   jRadioButton1.setContentAreaFilled(true);
                   jRadioButton1.setSelected(true);
                   jRadioButton1.setForeground(new Color(204,51,0));break;
                   case 2:jRadioButton2.setVisible(true);
                   jRadioButton2.setContentAreaFilled(true);
                   jRadioButton2.setSelected(true);
                   jRadioButton2.setForeground(new Color(204,51,0));
                   jRadioButton1.setForeground(Color.cyan);break;
                   case 3:jRadioButton3.setVisible(true);
                   jRadioButton3.setContentAreaFilled(true);
                   jRadioButton3.setSelected(true);
                   jRadioButton3.setForeground(new Color(204,51,0));
                   jRadioButton2.setForeground(Color.cyan);break;
                   case 4:jRadioButton4.setVisible(true);
                   jRadioButton4.setContentAreaFilled(true);
                   jRadioButton4.setSelected(true);
                   jRadioButton4.setForeground(new Color(204,51,0));
                   jRadioButton3.setForeground(Color.cyan);break;
                   case 5:jRadioButton5.setVisible(true);
                   jRadioButton5.setContentAreaFilled(true);
                   jRadioButton5.setSelected(true);
                   jRadioButton5.setForeground(new Color(204,51,0));
                   jRadioButton4.setForeground(Color.cyan);break;
                   case 6:jRadioButton6.setVisible(true);
                   jRadioButton6.setContentAreaFilled(true);
                   jRadioButton6.setSelected(true);
                   jRadioButton6.setForeground(new Color(204,51,0));
                   jRadioButton5.setForeground(Color.cyan);break;
                   case 7:jRadioButton7.setVisible(true);
                   jRadioButton7.setContentAreaFilled(true);
                   jRadioButton7.setSelected(true);
                   jRadioButton7.setForeground(new Color(204,51,0));
                   jRadioButton6.setForeground(Color.cyan);break;
                   case 8:jRadioButton8.setVisible(true);
                   jRadioButton8.setContentAreaFilled(true);
                   jRadioButton8.setSelected(true);
                   jRadioButton8.setForeground(new Color(204,51,0));
                   jRadioButton7.setForeground(Color.cyan);break;
                   case 9:jRadioButton9.setVisible(true);
                   jRadioButton9.setContentAreaFilled(true);
                   jRadioButton9.setSelected(true);
                   jRadioButton9.setForeground(new Color(204,51,0));
                   jRadioButton8.setForeground(Color.cyan);break;
                   case 10:jRadioButton10.setVisible(true);
                   jRadioButton10.setContentAreaFilled(true);
                   jRadioButton10.setSelected(true);
                   jRadioButton10.setForeground(new Color(204,51,0));
                   jRadioButton9.setForeground(Color.cyan);break;
                   case 11:jRadioButton11.setVisible(true);
                   jRadioButton11.setContentAreaFilled(true);
                   jRadioButton11.setSelected(true);
                   jRadioButton11.setForeground(new Color(204,51,0));
                   jRadioButton10.setForeground(Color.cyan);break;
                   case 12:jRadioButton12.setVisible(true);
                   jRadioButton12.setContentAreaFilled(true);
                   jRadioButton12.setSelected(true);
                   jRadioButton12.setForeground(new Color(204,51,0));
                   jRadioButton11.setForeground(Color.cyan);break;
                   case 13:jRadioButton13.setVisible(true);
                   jRadioButton13.setContentAreaFilled(true);
                   jRadioButton13.setSelected(true);
                   jRadioButton13.setForeground(new Color(204,51,0));
                   jRadioButton12.setForeground(Color.cyan);break;
                   case 14:jRadioButton14.setVisible(true);
                   jRadioButton14.setContentAreaFilled(true);
                   jRadioButton14.setSelected(true);
                   jRadioButton14.setForeground(new Color(204,51,0));
                   jRadioButton13.setForeground(Color.cyan);break;
                   case 15:jRadioButton15.setVisible(true);
                   jRadioButton15.setContentAreaFilled(true);
                   jRadioButton15.setSelected(true);
                   jRadioButton15.setForeground(new Color(204,51,0));
                   jRadioButton14.setForeground(Color.cyan);break;
                   case 16:jRadioButton15.setForeground(Color.cyan);
                   buttonGroup1.clearSelection();break;
                   default: break;
               }
     }
     });
        t.start();   break;
            case 2: jTextArea1.setText("The first 6 questions will be under a timer of 60 seconds.\nThe next 5 questions will be under a timer of 90 seconds.\nThe last 4 questions will not be timer bound. ");
                    buttonGroup1.clearSelection();                  
                    jRadioButton1.setVisible(true);
                    jRadioButton2.setVisible(true);
                    jRadioButton3.setVisible(true);
                    jRadioButton4.setVisible(true);
                    jRadioButton5.setVisible(true);
                    jRadioButton6.setVisible(true);
                    jRadioButton7.setVisible(true);
                    jRadioButton8.setVisible(true);
                    jRadioButton9.setVisible(true);
                    jRadioButton10.setVisible(true);
                    jRadioButton11.setVisible(true);
                    jRadioButton12.setVisible(true);
                    jRadioButton13.setVisible(true);
                    jRadioButton14.setVisible(true);
                    jRadioButton15.setVisible(true);
                    jRadioButton1.setForeground(Color.cyan);
                    jRadioButton2.setForeground(Color.cyan);
                    jRadioButton3.setForeground(Color.cyan);
                    jRadioButton4.setForeground(Color.cyan);
                    jRadioButton5.setForeground(Color.cyan);
                    jRadioButton6.setForeground(Color.cyan);
                    jRadioButton7.setForeground(Color.cyan);
                    jRadioButton8.setForeground(Color.cyan);
                    jRadioButton9.setForeground(Color.cyan);
                    jRadioButton10.setForeground(Color.cyan);
                    jRadioButton11.setForeground(Color.cyan);
                    jRadioButton12.setForeground(Color.cyan);
                    jRadioButton13.setForeground(Color.cyan);
                    jRadioButton14.setForeground(Color.cyan);
                    jRadioButton15.setForeground(Color.cyan);
                    jRadioButton1.setContentAreaFilled(true);
                    jRadioButton2.setContentAreaFilled(true);
                    jRadioButton3.setContentAreaFilled(true);
                    jRadioButton4.setContentAreaFilled(true);
                    jRadioButton5.setContentAreaFilled(true);
                    jRadioButton6.setContentAreaFilled(true);
                    jRadioButton7.setContentAreaFilled(true);
                    jRadioButton8.setContentAreaFilled(true);
                    jRadioButton9.setContentAreaFilled(true);
                    jRadioButton10.setContentAreaFilled(true);
                    jRadioButton11.setContentAreaFilled(true);
                    jRadioButton12.setContentAreaFilled(true);
                    jRadioButton13.setContentAreaFilled(true);
                    jRadioButton14.setContentAreaFilled(true);
                    jRadioButton15.setContentAreaFilled(true);
                    t.stop();
            break;
            case 3: jTextArea1.setText("The game has two safety 'Padaos' and reaching them will ensure that you win atleast that much prize money.\n The first padao is at the 6th question with a prize money of Rs 1,60,000. \n The second padao is at the 11th question with a prize money of Rs 50,00,000. ");
                    jRadioButton6.setForeground(Color.red);
                    jRadioButton11.setForeground(Color.red);
                    jRadioButton15.setForeground(Color.red);
                    t.stop();    break;
            case 5: jRadioButton1.setVisible(true);
                    jRadioButton2.setVisible(true);
                    jRadioButton3.setVisible(true);
                    jRadioButton4.setVisible(true);
                    jRadioButton5.setVisible(true);
                    jRadioButton6.setVisible(true);
                    jRadioButton7.setVisible(true);
                    jRadioButton8.setVisible(true);
                    jRadioButton9.setVisible(true);
                    jRadioButton10.setVisible(true);
                    jRadioButton11.setVisible(true);
                    jRadioButton12.setVisible(true);
                    jRadioButton13.setVisible(true);
                    jRadioButton14.setVisible(true);
                    jRadioButton15.setVisible(true);
                    jTextArea1.setText("If you are stuck with any question there are 4 lifelines to help you out. They are - \n 1) Audience Poll - \nThis lifeline will carry out an online voting , the results of which will be displayed on the screen. \n 2) Flip -\nThis lifeline allows you to change the question.  \n 3) 50-50 -\nThis lifeline will eliminate 2 incorrect options.\n 4) Power - Paplu -\n This lifeline will allow you to revive 1 of the above given lifelines");
                    jLabel3.setVisible(true);
                    jLabel4.setVisible(true);
                    jLabel5.setVisible(true);
                    jLabel2.setVisible(true);
                    t.stop(); break;
            case 4: jTextArea1.setText("Sufficient time has been given to all the questions, so think well before you answer as givng a wrong answer will reduce the value of your prize money as set by the padaos.\nYou can also quit if not sure about the answer to leave with the amount you have won till then. ");
                    t.stop(); h.stop(); x=0; jLabel2.setVisible(false);
                    jLabel3.setVisible(false);
                    jLabel4.setVisible(false);
                    jLabel5.setVisible(false);  break;
                    default:t.stop();jTextArea1.setText("Press the Back button to view previous rule\nPress the Next button to view next rule\nPress the Back to Home button to return to the Welcome Page");
        }  
        if(a==0)
        {
        jButton2.setVisible(false);
        jLabel2.setVisible(false);
        jLabel3.setVisible(false);
        jLabel4.setVisible(false);
        jLabel5.setVisible(false);
        jRadioButton1.setVisible(false);
        jRadioButton2.setVisible(false);
        jRadioButton3.setVisible(false);
        jRadioButton4.setVisible(false);
        jRadioButton5.setVisible(false);
        jRadioButton6.setVisible(false);
        jRadioButton7.setVisible(false);
        jRadioButton8.setVisible(false);
        jRadioButton9.setVisible(false);
        jRadioButton10.setVisible(false);
        jRadioButton11.setVisible(false);
        jRadioButton12.setVisible(false);
        jRadioButton13.setVisible(false);
        jRadioButton14.setVisible(false);
        jRadioButton15.setVisible(false);
        }
        else
        {
            jButton2.setVisible(true);
        }
        if(a==6)
        {
            jButton1.setVisible(false);
            jLabel2.setVisible(false);
        jLabel3.setVisible(false);
        jLabel4.setVisible(false);
        jLabel5.setVisible(false);
        jRadioButton1.setVisible(false);
        jRadioButton2.setVisible(false);
        jRadioButton3.setVisible(false);
        jRadioButton4.setVisible(false);
        jRadioButton5.setVisible(false);
        jRadioButton6.setVisible(false);
        jRadioButton7.setVisible(false);
        jRadioButton8.setVisible(false);
        jRadioButton9.setVisible(false);
        jRadioButton10.setVisible(false);
        jRadioButton11.setVisible(false);
        jRadioButton12.setVisible(false);
        jRadioButton13.setVisible(false);
        jRadioButton14.setVisible(false);
        jRadioButton15.setVisible(false);
        }
        else
        {
            jButton1.setVisible(true);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
Welcome_Page a= new Welcome_Page();
a.setVisible(true);
this.setVisible(false);  
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Rule_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Rule_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Rule_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Rule_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Rule_Page().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton10;
    private javax.swing.JRadioButton jRadioButton11;
    private javax.swing.JRadioButton jRadioButton12;
    private javax.swing.JRadioButton jRadioButton13;
    private javax.swing.JRadioButton jRadioButton14;
    private javax.swing.JRadioButton jRadioButton15;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JRadioButton jRadioButton9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
